# Default values for hzero-gateway-helper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.choerodon.com.cn/hzero-hzero/hzero-gateway-helper
  pullPolicy: Always

env:
  open:
    # 项目级API是否必须检查项目参数
    HZERO_GATEWAY_FILTER_COMMON-REQUEST_CHECK-PROJECT: true
    # 组织级API是否必须检查组织参数
    HZERO_GATEWAY_FILTER_COMMON-REQUEST_CHECK-ORGANIZATION: true
    # 开发者带数字后缀的不检查权限
    HZERO_GATEWAY_FILTER_DEVELOPER_ENABLED: false
    # 是否统计API访问情况
    HZERO_GATEWAY_FILTER_COLLECT_SPAN_ENABLED: false
    HZERO_DB_OWNER:
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka/
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    # 是否启用配置中心，默认会从配置中心拉取服务路由信息
    SPRING_CLOUD_CONFIG_ENABLED: true
    # 配置中心地址
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.org:8010/
    # 获取UserDetails地址
    SECURITY_OAUTH2_USER_INFO_URI: http://hzero-oauth/oauth/api/user
    # 数据库地址
    SPRING_DATASOURCE_URL: jdbc:mysql://db.hzero.org:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
    # 数据库用户名
    SPRING_DATASOURCE_USERNAME: root
    # 数据库密码
    SPRING_DATASOURCE_PASSWORD: 123456
    # Redis 地址
    SPRING_REDIS_HOST: redis.hzero.org
    # Redis DB
    SPRING_REDIS_DATABASE: 4
    # 连接超时时间
    ZUUL_HOST_CONNECT_TIMEOUT_MILLIS: 40000
    ZUUL_HOST_SOCKET_TIMEOUT_MILLIS: 40000
    # 熔断超时时间
    HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS: 40000
    # Ribbon 读取超时时间
    RIBBON_READ_TIMEOUT: 30000
    # Ribbon 连接超时时间
    RIBBON_CONNECT_TIMEOUT: 3000
    # 日志级别
    LOGGING_LEVEL: info
    JAVA_OPTS: >
      -Xms1024m
      -Xmx1536m
metrics:
  path: /prometheus
  group: spring-boot

logs:
 parser: spring-boot

persistence:
  enabled: false

service:
  enabled: false
  type: ClusterIP
  port: 8090
  name: hzero-gateway-helper

deployment:
  managementPort: 8091

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1.7Gi
  requests:
    # cpu: 100m
    memory: 1.2Gi

hzero:
  HZERO_NODE_GROUP_ID: 0
  HZERO_PRODUCT_CODE: DEFAULT
  HZERO_PRODUCT_VERSION_CODE: DEFAULT
  HZERO_PRODUCT_ENV_CODE: DEFAULT
  HZERO_SERVICE_VERSION_CODE: DEFAULT
